TARGET = ThesisProject
QT += core \
    gui
HEADERS += GUI/About/about.h \
    DynamicGestureRecognition/src/Association.h \
    QtOpenCV/qcv/qcvcg.h \
    QtOpenCV/qcv/qcvimage.h \
    QtOpenCV/qcv/qcvmovie.h \
    QtOpenCV/qcv/qcvpainter.h \
    QtOpenCV/qcv/qcvtypes.h \
    QtOpenCV/qcv/qcvwidget.h \
    QtOpenCV/qcv/qtopencv.h \
    XML/XMLStreamWriter.h \
    XML/XmlStreamReader.h \
    DynamicGestureRecognition/Initializer/InitTrainer.h \
    Camera/CameraVideo.h \
    Camera/Camera.h \
    GUI/HandDiagnostic/handdiagnostic.h \
    GUI/Utils/Container.h \
    Init/Main/Init.h \
    GUI/MovementGraph/paintmovement.h \
    GUI/newGesture/newgesture.h \
    DynamicGestureRecognition/Events/OpenFileEvent.h \
    DynamicGestureRecognition/Events/ExecuteApplication.h \
    DynamicGestureRecognition/Events/CombinedKeyPressed.h \
    DynamicGestureRecognition/Events/PressCharEvent.h \
    DynamicGestureRecognition/src/EventModel.h \
    Init/InitVisualizer.h \
    Init/ThesisStart.h \
    GUI/Estado/stateviewer.h \
    GUI/AddAsociation/addasociation.h \
    GUI/AddGesture/addgesture.h \
    GUI/AddEvent/addevent.h \
    GUI/CamViewer.h \
    DynamicGestureRecognition/src/Event.h \
    DynamicGestureRecognition/src/Gesture.h \
    DynamicGestureRecognition/src/GestureEventMapper.h \
    DynamicGestureRecognition/src/GestureModel.h \
    DynamicGestureRecognition/src/GestureModelHandler.h \
    DynamicGestureRecognition/src/GestureRecognizer.h \
    DynamicGestureRecognition/src/SignalRefactor.h \
    DynamicGestureRecognition/src/ValuesNormalizator.h \
    Fann/include/compat_time.h \
    Fann/include/config.h \
    Fann/include/doublefann.h \
    Fann/include/fann.h \
    Fann/include/fann_activation.h \
    Fann/include/fann_cascade.h \
    Fann/include/fann_data.h \
    Fann/include/fann_error.h \
    Fann/include/fann_internal.h \
    Fann/include/fann_io.h \
    Fann/include/fann_train.h \
    Fann/include/fixedfann.h \
    Fann/include/floatfann.h \
    Filters/DownSamplingFilter.h \
    Filters/FIRfilter.h \
    Filters/FilterHandler.h \
    Filters/GrayFilter.h \
    Filters/ImageFilter.h \
    Filters/NormalFilter.h \
    Filters/SkinFilter.h \
    Init/InitTracker.h \
    Logger/LogHandler.h \
    NeuralNetwork/GestureNeuralNet.h \
    NeuralNetwork/NeuralNet.h \
    Utils/ImageUtilities.h \
    Utils/SystemInfo.h \
    stabilizers/LightStabilizer.h \
    Camera/CamHandler.h \
    CommonProject/InterfaceWorker/Initializer.h \
    CommonProject/InterfaceWorker/InitializerCreator.h \
    CommonProject/Threads/Thread_Tracker.h \
    CommonProject/Threads/Thread_Worker.h \
    CommonProject/src/Buffer_PC.h \
    CommonProject/src/CoordsGetter.h \
    CommonProject/src/CoordsSaver.h \
    ConfigurationHandler/ConfigHandler.h \
    CursorHandler/src/Initializer/InitCursor.h \
    CursorHandler/src/cursorVisualizer.h \
    DynamicGestureRecognition/ActivationGestureMethods/AccelerationActivation.h \
    DynamicGestureRecognition/ActivationGestureMethods/TrainingActivationGestureMethod.h \
    DynamicGestureRecognition/CircularBuffer/CircularBuffer.h \
    DynamicGestureRecognition/DTWAlgorithms/ItakuraDTWAlgorithm.h \
    DynamicGestureRecognition/DTWAlgorithms/RawDTWAlgorithm.h \
    DynamicGestureRecognition/DTWAlgorithms/SakoeChibaDTWAlgorithm.h \
    DynamicGestureRecognition/DistanceCalculators/EuclideanDistance.h \
    DynamicGestureRecognition/Events/DoNothingEvent.h \
    DynamicGestureRecognition/Events/PrintCharEvent.h \
    DynamicGestureRecognition/Gestures/NoGestureDetected.h \
    DynamicGestureRecognition/Initializer/InitDynamicGestureRecognition.h \
    DynamicGestureRecognition/src/ActivationGestureMethod.h \
    DynamicGestureRecognition/src/DTWAlgorithm.h \
    DynamicGestureRecognition/src/DTWData.h \
    DynamicGestureRecognition/src/DTWDataHandler.h \
    DynamicGestureRecognition/src/DistanceCalculator.h \
    DynamicGestureRecognition/src/DynamicGestureRecognitionAlgorithm.h \
    DynamicGestureRecognition/src/addGesturePolicy.h \
    mainwindow.h
SOURCES += GUI/About/about.cpp \
    DynamicGestureRecognition/src/Association.cpp \
    QtOpenCV/qcv/qcvcg.cpp \
    QtOpenCV/qcv/qcvimage.cpp \
    QtOpenCV/qcv/qcvmovie.cpp \
    QtOpenCV/qcv/qcvpainter.cpp \
    QtOpenCV/qcv/qcvtypes.cpp \
    QtOpenCV/qcv/qcvwidget.cpp \
    QtOpenCV/qcv/qtopencv.cpp \
    XML/XMLStreamWriter.cpp \
    XML/XmlStreamReader.cpp \
    DynamicGestureRecognition/Initializer/InitTrainer.cpp \
    Camera/CameraVideo.cpp \
    Camera/Camera.cpp \
    GUI/HandDiagnostic/handdiagnostic.cpp \
    GUI/Utils/Container.cpp \
    Init/Main/Init.cpp \
    GUI/MovementGraph/paintmovement.cpp \
    GUI/newGesture/newgesture.cpp \
    DynamicGestureRecognition/Events/OpenFileEvent.cpp \
    DynamicGestureRecognition/Events/ExecuteApplication.cpp \
    DynamicGestureRecognition/Events/CombinedKeyPressed.cpp \
    DynamicGestureRecognition/Events/PressCharEvent.cpp \
    DynamicGestureRecognition/src/EventModel.cpp \
    Init/InitVisualizer.cpp \
    Init/ThesisStart.cpp \
    GUI/Estado/stateviewer.cpp \
    GUI/AddAsociation/addasociation.cpp \
    GUI/AddGesture/addgesture.cpp \
    GUI/AddEvent/addevent.cpp \
    GUI/CamViewer.cpp \
    DynamicGestureRecognition/src/Gesture.cpp \
    DynamicGestureRecognition/src/GestureEventMapper.cpp \
    DynamicGestureRecognition/src/GestureModel.cpp \
    DynamicGestureRecognition/src/GestureModelHandler.cpp \
    DynamicGestureRecognition/src/GestureRecognizer.cpp \
    DynamicGestureRecognition/src/SignalRefactor.cpp \
    DynamicGestureRecognition/src/ValuesNormalizator.cpp \
    Filters/DownSamplingFilter.cpp \
    Filters/FIRfilter.cpp \
    Filters/FilterHandler.cpp \
    Filters/GrayFilter.cpp \
    Filters/ImageFilter.cpp \
    Filters/NormalFilter.cpp \
    Filters/SkinFilter.cpp \
    Init/InitTracker.cpp \
    Init/tracker.cpp \
    Logger/LogHandler.cpp \
    NeuralNetwork/GestureNeuralNet.cpp \
    NeuralNetwork/NeuralNet.cpp \
    Utils/ImageUtilities.cpp \
    Utils/SystemInfo.cpp \
    stabilizers/LightStabilizer.cpp \
    Camera/CamHandler.cpp \
    CommonProject/InterfaceWorker/Initializer.cpp \
    CommonProject/InterfaceWorker/InitializerCreator.cpp \
    CommonProject/Threads/Thread_Tracker.cpp \
    CommonProject/Threads/Thread_Worker.cpp \
    CommonProject/src/Buffer_PC.cpp \
    CommonProject/src/CoordsGetter.cpp \
    CommonProject/src/CoordsSaver.cpp \
    ConfigurationHandler/ConfigHandler.cpp \
    CursorHandler/src/Initializer/InitCursor.cpp \
    CursorHandler/src/cursorVisualizer.cpp \
    DynamicGestureRecognition/ActivationGestureMethods/AccelerationActivation.cpp \
    DynamicGestureRecognition/ActivationGestureMethods/TrainingActivationGestureMethod.cpp \
    DynamicGestureRecognition/CircularBuffer/CircularBuffer.cpp \
    DynamicGestureRecognition/DTWAlgorithms/ItakuraDTWAlgorithm.cpp \
    DynamicGestureRecognition/DTWAlgorithms/RawDTWAlgorithm.cpp \
    DynamicGestureRecognition/DTWAlgorithms/SakoeChibaDTWAlgorithm.cpp \
    DynamicGestureRecognition/DistanceCalculators/EuclideanDistance.cpp \
    DynamicGestureRecognition/Events/DoNothingEvent.cpp \
    DynamicGestureRecognition/Events/PrintCharEvent.cpp \
    DynamicGestureRecognition/Gestures/NoGestureDetected.cpp \
    DynamicGestureRecognition/Initializer/InitDynamicGestureRecognition.cpp \
    DynamicGestureRecognition/src/ActivationGestureMethod.cpp \
    DynamicGestureRecognition/src/DTWAlgorithm.cpp \
    DynamicGestureRecognition/src/DTWData.cpp \
    DynamicGestureRecognition/src/DTWDataHandler.cpp \
    DynamicGestureRecognition/src/DistanceCalculator.cpp \
    DynamicGestureRecognition/src/DynamicGestureRecognitionAlgorithm.cpp \
    DynamicGestureRecognition/src/Event.cpp \
    DynamicGestureRecognition/src/addGesturePolicy.cpp \
    main.cpp \
    mainwindow.cpp
FORMS += GUI/About/about.ui \
    GUI/HandDiagnostic/handdiagnostic.ui \
    GUI/MovementGraph/paintmovement.ui \
    GUI/newGesture/newgesture.ui \
    GUI/Estado/stateviewer.ui \
    GUI/AddAsociation/addasociation.ui \
    GUI/AddGesture/addgesture.ui \
    GUI/AddEvent/addevent.ui \
    mainwindow.ui
RESOURCES += Resources/resources.qrc
INCLUDEPATH += 'C:/Program \
    Files/OpenCV/otherlibs/highgui' \
    'C:/Program \
    Files/OpenCV/cvaux/include' \
    'C:/Program \
    Files/OpenCV/cv/include' \
    'C:/Program \
    Files/OpenCV/cxcore/include'
LIBS += -L'C:/Program \
    Files/OpenCV/lib' \
    -lhighgui \
    -lcxcore \
    -lcv
LIBS += -L'C:/fann-2.0.0/lib' \
    -lFann20
